In [1]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("country_vaccinations.csv")
print(df.head())

       country iso_code       date  total_vaccinations  people_vaccinated  \
0  Afghanistan      AFG  2/22/2021                 0.0                0.0
1  Afghanistan      AFG  2/23/2021                 NaN                NaN
2  Afghanistan      AFG  2/24/2021                 NaN                NaN
3  Afghanistan      AFG  2/25/2021                 NaN                NaN
4  Afghanistan      AFG  2/26/2021                 NaN                NaN

   people_fully_vaccinated  daily_vaccinations_raw  daily_vaccinations  \
0                      NaN                     NaN                 NaN
1                      NaN                     NaN              1367.0
2                      NaN                     NaN              1367.0
3                      NaN                     NaN              1367.0
4                      NaN                     NaN              1367.0

   total_vaccinations_per_hundred  people_vaccinated_per_hundred  \
0                             0.0                            0.0
1                             NaN                            NaN
2                             NaN                            NaN
3                             NaN                            NaN
4                             NaN                            NaN

   people_fully_vaccinated_per_hundred  daily_vaccinations_per_million  \
0                                  NaN                             NaN
1                                  NaN                            35.0
2                                  NaN                            35.0
3                                  NaN                            35.0
4                                  NaN                            35.0

                                          vaccines                source_name  \
0  BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech  World Health Organization
1  BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech  World Health Organization
2  BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech  World Health Organization
3  BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech  World Health Organization
4  BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech  World Health Organization

             source_website
0  https://covid19.who.int/
1  https://covid19.who.int/
2  https://covid19.who.int/
3  https://covid19.who.int/
4  https://covid19.who.int/

In [ ]:
df.shape

(25862, 15)

In [4]:
df.tail()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
25857,Zimbabwe,ZWE,6/16/2021,1120873.0,697399.0,423474.0,7395.0,5270.0,7.54,4.69,2.85,355.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1406690528...
25858,Zimbabwe,ZWE,6/17/2021,1126087.0,698953.0,427134.0,5214.0,5226.0,7.58,4.70,2.87,352.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1406690528...
25859,Zimbabwe,ZWE,6/18/2021,1131397.0,700244.0,431153.0,5310.0,4935.0,7.61,4.71,2.90,332.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1406690528...
25860,Zimbabwe,ZWE,6/19/2021,1133920.0,701348.0,432572.0,2523.0,4360.0,7.63,4.72,2.91,293.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1406690528...
25861,Zimbabwe,ZWE,6/20/2021,1138733.0,703065.0,435668.0,4813.0,4525.0,7.66,4.73,2.93,304.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1406690528...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25862 entries, 0 to 25861
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              25862 non-null  object
 1   iso_code                             25862 non-null  object
 2   date                                 25862 non-null  object
 3   total_vaccinations                   14522 non-null  float64
 4   people_vaccinated                    13762 non-null  float64
 5   people_fully_vaccinated              11041 non-null  float64
 6   daily_vaccinations_raw               12003 non-null  float64
 7   daily_vaccinations                   25595 non-null  float64
 8   total_vaccinations_per_hundred       14522 non-null  float64
 9   people_vaccinated_per_hundred        13762 non-null  float64
 10  people_fully_vaccinated_per_hundred  11041 non-null  float64
 11  daily_vaccinations_per_million       25595 non-null  float64
 12  vaccines                             25862 non-null  object
 13  source_name                          25862 non-null  object
 14  source_website                       25862 non-null  object
dtypes: float64(9), object(6)
memory usage: 3.0+ MB

In [6]:
df.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,1.452200e+04,1.376200e+04,1.104100e+04,1.200300e+04,2.559500e+04,14522.000000,13762.000000,11041.000000,25595.000000
mean,9.139252e+06,4.737802e+06,2.681353e+06,2.012910e+05,1.020430e+05,24.162602,16.291051,9.712350,3312.476421
std,4.592776e+07,1.797156e+07,1.093032e+07,1.122962e+06,7.304361e+05,30.690367,18.839369,13.466102,4512.443697
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,1.005620e+05,7.876700e+04,3.719700e+04,3.967500e+03,8.400000e+02,2.360000,2.052500,1.020000,389.000000
50%,7.007560e+05,5.149065e+05,2.834740e+05,1.988600e+04,6.263000e+03,11.410000,8.520000,4.190000,1726.000000
75%,3.241681e+06,2.139073e+06,1.192415e+06,8.257600e+04,3.337300e+04,34.650000,25.207500,12.690000,4874.000000
max,1.029223e+09,6.220000e+08,2.232990e+08,2.360500e+07,2.029871e+07,231.010000,116.150000,114.860000,118759.000000

In [7]:
df.describe(include='object')

,country,iso_code,date,vaccines,source_name,source_website
count,25862,25862,25862,25862,25862,25862
unique,217,217,201,56,95,150
top,Norway,NOR,5/12/2021,Oxford/AstraZeneca,Ministry of Health,https://covid19.who.int/
freq,201,201,207,4326,6732,4324

In [8]:
df['date'] = pd.to_datetime(df['date'])
df['date'].dtype
print(df['date'].min())
print(df['date'].max())

2020-12-02 00:00:00
2021-06-20 00:00:00

In [9]:
df.isnull().sum()

country                                    0
iso_code                                   0
date                                       0
total_vaccinations                     11340
people_vaccinated                      12100
people_fully_vaccinated                14821
daily_vaccinations_raw                 13859
daily_vaccinations                       267
total_vaccinations_per_hundred         11340
people_vaccinated_per_hundred          12100
people_fully_vaccinated_per_hundred    14821
daily_vaccinations_per_million           267
vaccines                                   0
source_name                                0
source_website                             0
dtype: int64

In [10]:
df.isnull().mean() * 100 ##Tỷ lệ missing

country                                 0.000000
iso_code                                0.000000
date                                    0.000000
total_vaccinations                     43.848117
people_vaccinated                      46.786791
people_fully_vaccinated                57.308019
daily_vaccinations_raw                 53.588276
daily_vaccinations                      1.032403
total_vaccinations_per_hundred         43.848117
people_vaccinated_per_hundred          46.786791
people_fully_vaccinated_per_hundred    57.308019
daily_vaccinations_per_million          1.032403
vaccines                                0.000000
source_name                             0.000000
source_website                          0.000000
dtype: float64

In [11]:
df.isnull().sum().sort_values(ascending=False)

people_fully_vaccinated                14821
people_fully_vaccinated_per_hundred    14821
daily_vaccinations_raw                 13859
people_vaccinated_per_hundred          12100
people_vaccinated                      12100
total_vaccinations                     11340
total_vaccinations_per_hundred         11340
daily_vaccinations_per_million           267
daily_vaccinations                       267
date                                       0
country                                    0
iso_code                                   0
vaccines                                   0
source_name                                0
source_website                             0
dtype: int64

In [12]:
df.select_dtypes(include='object').columns

Index(['country', 'iso_code', 'vaccines', 'source_name', 'source_website'], dtype='object')

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['vaccines'].value_counts()

vaccines
Oxford/AstraZeneca                                                                             4326
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech                                  3437
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech                                                   2222
Oxford/AstraZeneca, Pfizer/BioNTech                                                            1697
Moderna, Pfizer/BioNTech                                                                       1394
Pfizer/BioNTech                                                                                1143
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V                              1122
Oxford/AstraZeneca, Sinopharm/Beijing                                                          1082
Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac                                                   1033
Oxford/AstraZeneca, Sputnik V                                                                   558
Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik V                                         499
Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V                                                462
BBIBP-CorV, Oxford/AstraZeneca                                                                  450
Johnson&Johnson, Moderna, Pfizer/BioNTech                                                       369
Oxford/AstraZeneca, Sinovac                                                                     364
Sinopharm/Beijing                                                                               306
BBIBP-CorV, Sputnik V                                                                           290
Pfizer/BioNTech, Sinovac                                                                        278
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing                                          268
Oxford/AstraZeneca, Sinovac, Sputnik V                                                          231
Moderna, Oxford/AstraZeneca                                                                     207
Covaxin, Oxford/AstraZeneca                                                                     192
EpiVacCorona, Sputnik V                                                                         188
CanSino, Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac                                            188
CanSino, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik V                                178
CanSino, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac                                           177
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V     171
Sinopharm/Beijing, Sputnik V                                                                    169
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinopharm/Wuhan, Sputnik V              167
BBIBP-CorV, Oxford/AstraZeneca, Sinovac, Sputnik V                                              148
BBIBP-CorV, Covaxin, Oxford/AstraZeneca                                                         147
Moderna                                                                                         143
QazVac, Sinopharm/HayatVax, Sputnik V                                                           141
CanSino, Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac, Sputnik V                              138
Pfizer/BioNTech, Sinopharm/Beijing                                                              133
Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac                                                  132
BBIBP-CorV, Covaxin, Oxford/AstraZeneca, Sputnik V                                              127
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac                                 126
Johnson&Johnson, Pfizer/BioNTech                                                                124
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik V                      122
Covaxin, Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac, Sputnik V                              117
Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech                                            116
Pfizer/BioNTech, Sputnik V                                                                      114
BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech                                                 113
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Sputnik V                                         111
BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech, Sputnik V                                      106
BBIBP-CorV, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac                                        103
Sputnik V                                                                                        81
Oxford/AstraZeneca, RBD-Dimer, Sputnik V                                                         77
BBIBP-CorV, Moderna, Oxford/AstraZeneca, Sputnik V                                               68
BBIBP-CorV, Oxford/AstraZeneca, Sinovac                                                          63
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik V                61
Covaxin, Oxford/AstraZeneca, Sinopharm/Beijing                                                   49
Abdala, Soberana02                                                                               32
BBIBP-CorV                                                                                        1
EpiVacCorona, Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V                                    1
Name: count, dtype: int64

In [20]:
df = df.dropna()

In [21]:
print(df.isna().sum())

country                                0
iso_code                               0
date                                   0
total_vaccinations                     0
people_vaccinated                      0
people_fully_vaccinated                0
daily_vaccinations_raw                 0
daily_vaccinations                     0
total_vaccinations_per_hundred         0
people_vaccinated_per_hundred          0
people_fully_vaccinated_per_hundred    0
daily_vaccinations_per_million         0
vaccines                               0
source_name                            0
source_website                         0
dtype: int64

In [23]:
df.to_csv("country_vaccinations_cleaned.csv", index=False)
print("Xuất file thành công")

Xuất file thành công

In [3]:
df_manufacture = pd.read_csv('country_vaccinations_by_manufacturer.csv')
df_manufacture.head(10)

  location       date        vaccine_name  total_vaccinations
0  Austria   1/5/2021     Johnson&Johnson                   0
1  Austria   1/5/2021             Moderna                   0
2  Austria   1/5/2021  Oxford/AstraZeneca                   0
3  Austria   1/5/2021     Pfizer/BioNTech               30885
4  Austria  1/12/2021     Johnson&Johnson                   0
5  Austria  1/12/2021             Moderna                  88
6  Austria  1/12/2021  Oxford/AstraZeneca                   0
7  Austria  1/12/2021     Pfizer/BioNTech              115203
8  Austria  1/19/2021     Johnson&Johnson                   0
9  Austria  1/19/2021             Moderna                 298

In [11]:
df_manufacture.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7517 entries, 0 to 7516
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location            7517 non-null   object
 1   date                7517 non-null   datetime64[ns]
 2   vaccine_name        7517 non-null   object
 3   total_vaccinations  7517 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 235.0+ KB

In [6]:
df_manufacture['date'] = pd.to_datetime(df_manufacture['date'])
df_manufacture['date'].dtype

dtype('<M8[ns]')

In [7]:
print(df_manufacture['date'].min())
print(df_manufacture['date'].max())

2020-12-24 00:00:00
2021-06-21 00:00:00

In [12]:
df_manufacture.isna().sum()

location              0
date                  0
vaccine_name          0
total_vaccinations    0
dtype: int64

In [13]:
df_manufacture.dtypes

location                      object
date                  datetime64[ns]
vaccine_name                  object
total_vaccinations             int64
dtype: object